=== krisling049/warcry_data/schemas/faction_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/schemas/faction_schema.json",
	"type": "object",
	"title": "Schema for faction data files",
	"required": [
		"grand_alliance",
		"warband",
		"bladeborn",
		"heroes_all",
		"subfactions"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this faction. In generated from the beginning of a uuid4.",
			"examples": [
				"c0fadcc5"
			]
		},
		"grand_alliance": {
			"type": "string",
			"description": "The name of the Grand Alliance that this faction belongs to, lowercased.",
			"examples": [
				"chaos"
			]
		},
		"warband": {
			"type": "string",
			"description": "The name of the faction runemark. Fighters and abilities refer to the faction by this name.",
			"examples": [
				"Blades of Khorne: Bloodbound"
			]
		},
		"bladeborn": {
			"type": "boolean",
			"description": "True if this faction has a Bladeborn runemark as its runemark, otherwise False"
		},
		"heroes_all": {
			"type": "boolean",
			"description": "True if this faction/subfaction is subject to a rule similar to the Questor Soulsworn 'Heroes All' rule"
		},
		"singleton": {
			"type": "boolean",
			"description": "True if this faction/subfaction contains only singleton fighters (max 1 of each fighter type)"
		},
		"subfactions": {
			"type": "array",
			"items": {
				"type": "object",
				"required": [
					"runemark",
					"bladeborn",
					"heroes_all"
				],
				"properties": {
					"runemark": {
						"type": "string",
						"description": "The name of the faction runemark",
						"examples": [
							"Blades of Khorne: Bloodbound"
						]
					},
					"bladeborn": {
						"type": "boolean",
						"description": "True if this faction has a Bladeborn runemark as its runemark, otherwise False"
					},
					"heroes_all": {
						"type": "boolean",
						"description": "True if this faction/subfaction is subject to a rule similar to the Questor Soulsworn 'Heroes All' rule"
					},
					"singleton": {
						"type": "boolean",
						"description": "True if this faction/subfaction contains only singleton fighters (max 1 of each fighter type)"
					}
				}
			}
		}
	}
}

=== krisling049/warcry_data/data/destruction/kruleboyz/kruleboyz_faction.json
{
    "grand_alliance": "destruction",
    "warband": "Kruleboyz",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "Daggok's Stab-ladz",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Da Kunnin' Krew",
            "bladeborn": true,
            "heroes_all": false
        }
    ]
}

=== krisling049/warcry_data/data/order/stormcast_eternals_thunderstrike_stormcast/stormcast_eternals_thunderstrike_stormcast_faction.json
{
    "grand_alliance": "order",
    "warband": "Stormcast Eternals Thunderstrike Stormcast",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "Xandire's Truthseekers",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Domitan's Stormcoven",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Gladitorium",
            "bladeborn": false,
            "heroes_all": true
        }
    ]
}

=== krisling049/warcry_data/data/order/seraphon/seraphon_faction.json
{
    "grand_alliance": "order",
    "warband": "Seraphon",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "The Starblood Stalkers",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Jaws of Itzl",
            "bladeborn": true,
            "heroes_all": true
        }
    ]
}
