=== krisling049/warcry_data/schemas/faction_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/schemas/faction_schema.json",
	"type": "object",
	"title": "Schema for faction data files",
	"required": [
		"grand_alliance",
		"warband",
		"bladeborn",
		"heroes_all",
		"subfactions"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this faction. In generated from the beginning of a uuid4.",
			"examples": [
				"c0fadcc5"
			]
		},
		"grand_alliance": {
			"type": "string",
			"description": "The name of the Grand Alliance that this faction belongs to, lowercased.",
			"examples": [
				"chaos"
			]
		},
		"warband": {
			"type": "string",
			"description": "The name of the faction runemark. Fighters and abilities refer to the faction by this name.",
			"examples": [
				"Blades of Khorne: Bloodbound"
			]
		},
		"bladeborn": {
			"type": "boolean",
			"description": "True if this faction has a Bladeborn runemark as its runemark, otherwise False"
		},
		"heroes_all": {
			"type": "boolean",
			"description": "True if this faction/subfaction is subject to a rule similar to the Questor Soulsworn 'Heroes All' rule"
		},
		"singleton": {
			"type": "boolean",
			"description": "True if this faction/subfaction contains only singleton fighters (max 1 of each fighter type)"
		},
		"subfactions": {
			"type": "array",
			"items": {
				"type": "object",
				"required": [
					"runemark",
					"bladeborn",
					"heroes_all"
				],
				"properties": {
					"runemark": {
						"type": "string",
						"description": "The name of the faction runemark",
						"examples": [
							"Blades of Khorne: Bloodbound"
						]
					},
					"bladeborn": {
						"type": "boolean",
						"description": "True if this faction has a Bladeborn runemark as its runemark, otherwise False"
					},
					"heroes_all": {
						"type": "boolean",
						"description": "True if this faction/subfaction is subject to a rule similar to the Questor Soulsworn 'Heroes All' rule"
					},
					"singleton": {
						"type": "boolean",
						"description": "True if this faction/subfaction contains only singleton fighters (max 1 of each fighter type)"
					}
				}
			}
		}
	}
}

=== krisling049/warcry_data/data/chaos/blades_of_khorne_bloodbound/blades_of_khorne_bloodbound_faction.json
{
    "grand_alliance": "chaos",
    "warband": "Blades of Khorne: Bloodbound",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "Garrek's Reavers",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Magore's Fiends",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Gorechosen of Dromm",
            "bladeborn": true,
            "heroes_all": false
        }
    ]
}

=== krisling049/warcry_data/data/chaos/slaves_to_darkness/slaves_to_darkness_faction.json
{
    "grand_alliance": "chaos",
    "warband": "Slaves to Darkness",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "Khagra's Ravagers",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Godsworn Hunt",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Gnarlspirit Pack",
            "bladeborn": true,
            "heroes_all": false
        }
    ]
}

=== krisling049/warcry_data/data/order/stormcast_eternals_sacrosanct_chamber/stormcast_eternals_sacrosanct_chamber_faction.json
{
    "grand_alliance": "order",
    "warband": "Stormcast Eternals Sacrosanct Chamber",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "Stormsire's Cursebreakers",
            "bladeborn": true,
            "heroes_all": false
        }
    ]
}

=== krisling049/warcry_data/data/death/nighthaunt/nighthaunt_faction.json
{
    "grand_alliance": "death",
    "warband": "Nighthaunt",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "The Headsmen's Curse",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Thorns of the Briar Queen",
            "bladeborn": true,
            "heroes_all": false
        }
    ]
}

=== krisling049/warcry_data/data/order/stormcast_eternals_vanguard_auxiliary_chamber/stormcast_eternals_vanguard_auxiliary_chamber_faction.json
{
    "grand_alliance": "order",
    "warband": "Stormcast Eternals Vanguard Auxiliary Chamber",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "The Farstriders",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "The Emberwatch",
            "bladeborn": true,
            "heroes_all": true
        }
    ]
}

=== krisling049/warcry_data/data/death/soulblight_gravelords/soulblight_gravelords_faction.json
{
    "grand_alliance": "death",
    "warband": "Soulblight Gravelords",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "Sons of Velmorn",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "The Crimson Court",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "The Exiled Dead",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "The Sepulchral Guard",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Zondara's Gravebreakers",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "The Blades of the Hollow King",
            "bladeborn": true,
            "heroes_all": true
        }
    ]
}

=== krisling049/warcry_data/data/destruction/ogor_mawtribes/ogor_mawtribes_faction.json
{
    "grand_alliance": "destruction",
    "warband": "Ogor Mawtribes",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "Blackpowder's Buccaneers",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Hrothgorn's Mantrappers",
            "bladeborn": true,
            "heroes_all": false
        }
    ]
}

=== krisling049/warcry_data/data/destruction/gloomspite_gitz/gloomspite_gitz_faction.json
{
    "grand_alliance": "destruction",
    "warband": "Gloomspite Gitz",
    "bladeborn": false,
    "heroes_all": false,
    "subfactions": [
        {
            "runemark": "Zarbag's Gitz",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Grinkrak's Looncourt",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Mollog's Mob",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Rippa's Snarlfangs",
            "bladeborn": true,
            "heroes_all": false
        },
        {
            "runemark": "Borgit's Beastgrabbaz",
            "bladeborn": true,
            "heroes_all": true
        }
    ]
}
