=== krisling049/warcry_data/schemas/fighter_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/schemas/fighter_schema.json",
	"type": "object",
	"title": "Fighter Schema",
	"required": [
		"_id",
		"subfaction",
		"grand_alliance",
		"movement",
		"name",
		"points",
		"runemarks",
		"toughness",
		"warband",
		"weapons",
		"wounds"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this fighter: 8 lowercase letters or digits, e.g. the start of a uuid4.",
			"pattern": "^[0-9a-z]{8}$",
			"examples": [
				"c0fadcc5"
			]
		},
		"subfaction": {
			"type": "string",
			"description": "If the fighter belongs to a subfaction, their subfaction warband name. Otherwise an empty string",
			"default": "",
			"examples": [
				"Hedrakka's Madmob"
			]
		},
		"grand_alliance": {
			"type": "string",
			"description": "Grand Alliance name, lowercase",
			"enum": [
				"chaos",
				"death",
				"destruction",
				"order"
			],
			"examples": [
				"destruction"
			]
		},
		"movement": {
			"type": "integer",
			"description": "Movement characteristic of the fighter",
			"examples": [
				4
			]
		},
		"name": {
			"type": "string",
			"description": "Name of the fighter as it appears on their profile card",
			"examples": [
				"Savage Orruk Arrowboy"
			]
		},
		"points": {
			"type": "integer",
			"description": "Points value of the fighter",
			"examples": [
				110
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		},
		"toughness": {
			"type": "integer",
			"description": "Toughness characteristic of the fighter",
			"examples": [
				3
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the fighter's faction, as defined by their faction runemark",
			"examples": [
				"Bonesplitterz"
			]
		},
		"weapons": {
			"type": "array",
			"description": "Each attack profile available to the fighter",
			"items": {
				"type": "object",
				"required": [
					"attacks",
					"dmg_crit",
					"dmg_hit",
					"max_range",
					"min_range",
					"runemark",
					"strength"
				],
				"properties": {
					"attacks": {
						"type": "integer",
						"examples": [
							3,
							2
						]
					},
					"dmg_crit": {
						"type": "integer",
						"examples": [
							2,
							3
						]
					},
					"dmg_hit": {
						"type": "integer",
						"examples": [
							1
						]
					},
					"max_range": {
						"type": "integer",
						"examples": [
							1,
							15
						]
					},
					"min_range": {
						"type": "integer",
						"description": "If no minimum range, use 0",
						"examples": [
							0,
							3
						]
					},
					"runemark": {
						"type": "string",
						"description": "Runemark of this weapon profile",
						"examples": [
							"unarmed",
							"ranged"
						]
					},
					"strength": {
						"type": "integer",
						"title": "The strength Schema",
						"examples": [
							3
						]
					}
				},
				"examples": [
					{
						"attacks": 3,
						"dmg_crit": 2,
						"dmg_hit": 1,
						"max_range": 1,
						"min_range": 0,
						"runemark": "unarmed",
						"strength": 3
					},
					{
						"attacks": 2,
						"dmg_crit": 3,
						"dmg_hit": 1,
						"max_range": 15,
						"min_range": 3,
						"runemark": "ranged",
						"strength": 3
					}
				]
			}
		},
		"wounds": {
			"type": "integer",
			"description": "Wounds characteristic of the fighter",
			"examples": [
				15
			]
		}
	},
	"examples": [
		{
			"_id": "c0fadcc5",
			"subfaction": "",
			"grand_alliance": "destruction",
			"movement": 4,
			"name": "Savage Orruk Arrowboy",
			"points": 110,
			"runemarks": [
				"destroyer"
			],
			"toughness": 3,
			"warband": "Bonesplitterz",
			"weapons": [
				{
					"attacks": 3,
					"dmg_crit": 2,
					"dmg_hit": 1,
					"max_range": 1,
					"min_range": 0,
					"runemark": "unarmed",
					"strength": 3
				},
				{
					"attacks": 2,
					"dmg_crit": 3,
					"dmg_hit": 1,
					"max_range": 15,
					"min_range": 3,
					"runemark": "ranged",
					"strength": 3
				}
			],
			"wounds": 15
		}
	]
}

=== krisling049/warcry_data/data/death/teratic_cohort/teratic_cohort_fighters.json
[
    {
        "_id": "0kvxvl2d",
        "name": "Kavalos Centari",
        "warband": "Teratic Cohort",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 7,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero",
            "elite",
            "mount"
        ],
        "points": 205
    },
    {
        "_id": "yofte4ap",
        "name": "Mortek Cykloptian with Dread Glaive",
        "warband": "Teratic Cohort",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "runemarks": [
            "elite"
        ],
        "points": 125
    },
    {
        "_id": "6ebtzcs3",
        "name": "Mortek Cykloptian with Nadirite Bident",
        "warband": "Teratic Cohort",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 5
            }
        ],
        "runemarks": [
            "elite"
        ],
        "points": 125
    },
    {
        "_id": "mg5be1qt",
        "name": "Teratic Prowler",
        "warband": "Teratic Cohort",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 3
            }
        ],
        "runemarks": [
            "beast"
        ],
        "points": 70
    },
    {
        "_id": "nqyjc38a",
        "name": "Aviarch Harpy",
        "warband": "Teratic Cohort",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 5,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 4
            }
        ],
        "runemarks": [
            "beast",
            "fly"
        ],
        "points": 105
    }
]

=== krisling049/warcry_data/data/chaos/iron_golems/iron_golems_fighters.json
[
    {
        "_id": "05730b23",
        "name": "Iron Legionary",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 5,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 75
    },
    {
        "_id": "4d002a1c",
        "name": "Iron Legionary with Bolas",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 75
    },
    {
        "_id": "4d8867a5",
        "name": "Iron Legionary with Twin Hammers",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 75
    },
    {
        "_id": "dec61d09",
        "name": "Armator",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 15,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 4
            }
        ],
        "runemarks": [],
        "points": 90
    },
    {
        "_id": "11ffa5a0",
        "name": "Signifer",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 4
            }
        ],
        "runemarks": [
            "icon-bearer"
        ],
        "points": 125
    },
    {
        "_id": "adc1715c",
        "name": "Prefector",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 4
            }
        ],
        "runemarks": [
            "brute"
        ],
        "points": 135
    },
    {
        "_id": "70b20681",
        "name": "Drillmaster",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 4
            },
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "runemarks": [
            "berserker"
        ],
        "points": 140
    },
    {
        "_id": "bb0df6f0",
        "name": "Dominar",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 22,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 5
            }
        ],
        "runemarks": [
            "hero",
            "brute"
        ],
        "points": 170
    },
    {
        "_id": "95f83304",
        "name": "Ogor Breacher",
        "warband": "Iron Golems",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 5,
        "wounds": 30,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 1,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 6
            }
        ],
        "runemarks": [
            "destroyer"
        ],
        "points": 220
    }
]

=== krisling049/warcry_data/data/chaos/spire_tyrants/spire_tyrants_fighters.json
[
    {
        "_id": "287ba04e",
        "name": "Pit Fighter with Net",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            }
        ],
        "runemarks": [
            "trapper"
        ],
        "points": 65
    },
    {
        "_id": "48c70d19",
        "name": "Pit Fighter with Punch Dagger",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 65
    },
    {
        "_id": "7ba499b7",
        "name": "Pit Fighter with Spear",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 65
    },
    {
        "_id": "ab224749",
        "name": "Frenzied Rager",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 15,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "warrior"
        ],
        "points": 95
    },
    {
        "_id": "7e7475df",
        "name": "Pit Veteran with Shield",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 5,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "warrior",
            "bulwark"
        ],
        "points": 100
    },
    {
        "_id": "2626a25d",
        "name": "Pit Veteran with Dual Weapons",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "warrior"
        ],
        "points": 105
    },
    {
        "_id": "4fcac576",
        "name": "Headclaimer",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 15,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "runemarks": [
            "brute"
        ],
        "points": 135
    },
    {
        "_id": "730e4623",
        "name": "Bestigor Destroyer",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "mace",
                "strength": 5
            }
        ],
        "runemarks": [
            "brute"
        ],
        "points": 145
    },
    {
        "_id": "b371dd35",
        "name": "Pit Champion",
        "warband": "Spire Tyrants",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 22,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 5
            },
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero"
        ],
        "points": 170
    }
]

=== krisling049/warcry_data/data/order/khainite_shadowstalkers/khainite_shadowstalkers_fighters.json
[
    {
        "_id": "40d5e9b6",
        "name": "Shroudblade with Cursed Swords",
        "warband": "Khainite Shadowstalkers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 6,
        "toughness": 3,
        "wounds": 8,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            }
        ],
        "runemarks": [
            "warrior"
        ],
        "points": 85
    },
    {
        "_id": "94e09fa1",
        "name": "Shroudblade with Umbral Spear",
        "warband": "Khainite Shadowstalkers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 6,
        "toughness": 3,
        "wounds": 8,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 4
            }
        ],
        "runemarks": [
            "warrior"
        ],
        "points": 85
    },
    {
        "_id": "101719f9",
        "name": "Darkflame Warlock with Repeater Crossbows",
        "warband": "Khainite Shadowstalkers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 6,
        "toughness": 3,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 3
            }
        ],
        "runemarks": [
            "mystic"
        ],
        "points": 100
    },
    {
        "_id": "13ce2d04",
        "name": "Darkflame Warlock with Doomfire Ring",
        "warband": "Khainite Shadowstalkers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 6,
        "toughness": 3,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "blast",
                "strength": 3
            },
            {
                "attacks": 2,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 7,
                "min_range": 3,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [
            "mystic"
        ],
        "points": 105
    },
    {
        "_id": "42aa3227",
        "name": "Slaughtershade with Umbral Spears",
        "warband": "Khainite Shadowstalkers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 6,
        "toughness": 3,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 4
            }
        ],
        "runemarks": [
            "warrior",
            "berserker"
        ],
        "points": 115
    },
    {
        "_id": "f9a82bda",
        "name": "Slaughtershade with Shadow Whip",
        "warband": "Khainite Shadowstalkers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 6,
        "toughness": 3,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "runemarks": [
            "warrior",
            "berserker"
        ],
        "points": 115
    },
    {
        "_id": "b8c2ba31",
        "name": "Shroud Queen",
        "warband": "Khainite Shadowstalkers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 6,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            },
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero"
        ],
        "points": 210
    }
]

=== krisling049/warcry_data/data/death/death/death_fighters.json
[
    {
        "_id": "58c57168",
        "name": "Dire Wolf",
        "warband": "death",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 8,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 3
            }
        ],
        "runemarks": [
            "thrall",
            "scout"
        ],
        "points": 85
    },
    {
        "_id": "61bbb21b",
        "name": "Fell Bat",
        "warband": "death",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 10,
        "toughness": 3,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 3
            }
        ],
        "runemarks": [
            "fly",
            "thrall",
            "frenzied"
        ],
        "points": 130
    },
    {
        "_id": "cc01fb56",
        "name": "Terrorgheist",
        "warband": "death",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 12,
        "toughness": 4,
        "wounds": 50,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "runemarks": [
            "fly",
            "monster",
            "terrifying"
        ],
        "points": 500
    },
    {
        "_id": "033e033b",
        "name": "Zombie Dragon",
        "warband": "death",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 12,
        "toughness": 4,
        "wounds": 50,
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 8,
                "dmg_hit": 4,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "runemarks": [
            "fly",
            "monster",
            "brute"
        ],
        "points": 540
    }
]
