=== krisling049/warcry_data/schemas/fighter_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/schemas/fighter_schema.json",
	"type": "object",
	"title": "Fighter Schema",
	"required": [
		"_id",
		"subfaction",
		"grand_alliance",
		"movement",
		"name",
		"points",
		"runemarks",
		"toughness",
		"warband",
		"weapons",
		"wounds"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this fighter: 8 lowercase letters or digits, e.g. the start of a uuid4.",
			"pattern": "^[0-9a-z]{8}$",
			"examples": [
				"c0fadcc5"
			]
		},
		"subfaction": {
			"type": "string",
			"description": "If the fighter belongs to a subfaction, their subfaction warband name. Otherwise an empty string",
			"default": "",
			"examples": [
				"Hedrakka's Madmob"
			]
		},
		"grand_alliance": {
			"type": "string",
			"description": "Grand Alliance name, lowercase",
			"enum": [
				"chaos",
				"death",
				"destruction",
				"order"
			],
			"examples": [
				"destruction"
			]
		},
		"movement": {
			"type": "integer",
			"description": "Movement characteristic of the fighter",
			"examples": [
				4
			]
		},
		"name": {
			"type": "string",
			"description": "Name of the fighter as it appears on their profile card",
			"examples": [
				"Savage Orruk Arrowboy"
			]
		},
		"points": {
			"type": "integer",
			"description": "Points value of the fighter",
			"examples": [
				110
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		},
		"toughness": {
			"type": "integer",
			"description": "Toughness characteristic of the fighter",
			"examples": [
				3
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the fighter's faction, as defined by their faction runemark",
			"examples": [
				"Bonesplitterz"
			]
		},
		"weapons": {
			"type": "array",
			"description": "Each attack profile available to the fighter",
			"items": {
				"type": "object",
				"required": [
					"attacks",
					"dmg_crit",
					"dmg_hit",
					"max_range",
					"min_range",
					"runemark",
					"strength"
				],
				"properties": {
					"attacks": {
						"type": "integer",
						"examples": [
							3,
							2
						]
					},
					"dmg_crit": {
						"type": "integer",
						"examples": [
							2,
							3
						]
					},
					"dmg_hit": {
						"type": "integer",
						"examples": [
							1
						]
					},
					"max_range": {
						"type": "integer",
						"examples": [
							1,
							15
						]
					},
					"min_range": {
						"type": "integer",
						"description": "If no minimum range, use 0",
						"examples": [
							0,
							3
						]
					},
					"runemark": {
						"type": "string",
						"description": "Runemark of this weapon profile",
						"examples": [
							"unarmed",
							"ranged"
						]
					},
					"strength": {
						"type": "integer",
						"title": "The strength Schema",
						"examples": [
							3
						]
					}
				},
				"examples": [
					{
						"attacks": 3,
						"dmg_crit": 2,
						"dmg_hit": 1,
						"max_range": 1,
						"min_range": 0,
						"runemark": "unarmed",
						"strength": 3
					},
					{
						"attacks": 2,
						"dmg_crit": 3,
						"dmg_hit": 1,
						"max_range": 15,
						"min_range": 3,
						"runemark": "ranged",
						"strength": 3
					}
				]
			}
		},
		"wounds": {
			"type": "integer",
			"description": "Wounds characteristic of the fighter",
			"examples": [
				15
			]
		}
	},
	"examples": [
		{
			"_id": "c0fadcc5",
			"subfaction": "",
			"grand_alliance": "destruction",
			"movement": 4,
			"name": "Savage Orruk Arrowboy",
			"points": 110,
			"runemarks": [
				"destroyer"
			],
			"toughness": 3,
			"warband": "Bonesplitterz",
			"weapons": [
				{
					"attacks": 3,
					"dmg_crit": 2,
					"dmg_hit": 1,
					"max_range": 1,
					"min_range": 0,
					"runemark": "unarmed",
					"strength": 3
				},
				{
					"attacks": 2,
					"dmg_crit": 3,
					"dmg_hit": 1,
					"max_range": 15,
					"min_range": 3,
					"runemark": "ranged",
					"strength": 3
				}
			],
			"wounds": 15
		}
	]
}

=== krisling049/warcry_data/data/chaos/splintered_fang/splintered_fang_fighters.json
[
    {
        "_id": "a0c2eb9f",
        "name": "Clearblood",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 65
    },
    {
        "_id": "298c9d36",
        "name": "Clearblood with Shield",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            }
        ],
        "runemarks": [
            "bulwark"
        ],
        "points": 65
    },
    {
        "_id": "8eef5146",
        "name": "Serpents",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 6,
        "toughness": 2,
        "wounds": 6,
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 3
            }
        ],
        "runemarks": [
            "beast"
        ],
        "points": 90
    },
    {
        "_id": "48930bbc",
        "name": "Venomblood with Blade and Barbed Whip",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            },
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 95
    },
    {
        "_id": "4e872f9a",
        "name": "Venomblood with Duelling Blades",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 95
    },
    {
        "_id": "e75b6a58",
        "name": "Venomblood with Barbed Whip",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 5,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "runemarks": [
            "bulwark"
        ],
        "points": 105
    },
    {
        "_id": "c17299c3",
        "name": "Venomblood with Spear and Shield",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 5,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 4
            }
        ],
        "runemarks": [
            "bulwark"
        ],
        "points": 105
    },
    {
        "_id": "d52caefd",
        "name": "Pureblood",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 4
            }
        ],
        "runemarks": [
            "brute"
        ],
        "points": 115
    },
    {
        "_id": "141590d5",
        "name": "Serpent Caller",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "toughness": 4,
        "wounds": 15,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [
            "mystic"
        ],
        "points": 145
    },
    {
        "_id": "58c9475c",
        "name": "Trueblood",
        "warband": "Splintered Fang",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero"
        ],
        "points": 170
    }
]

=== krisling049/warcry_data/data/chaos/scions_of_the_flame/scions_of_the_flame_fighters.json
[
    {
        "_id": "39ee76bf",
        "name": "Initiate with Flameburst Pot",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            }
        ],
        "runemarks": [
            "trapper"
        ],
        "points": 65
    },
    {
        "_id": "53e6f9b9",
        "name": "Initiate with Morning Star",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 65
    },
    {
        "_id": "0763fc24",
        "name": "Initiate with Brazier Weapon",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 4
            }
        ],
        "runemarks": [
            "trapper"
        ],
        "points": 70
    },
    {
        "_id": "4ec6ae25",
        "name": "Initiate with Hooked Axe",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 70
    },
    {
        "_id": "5e849cc1",
        "name": "Fireborn with Sunblade and Kris",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 95
    },
    {
        "_id": "89ae9d7f",
        "name": "Fireborn with Sunblade and Brazier Axe",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 4
            }
        ],
        "runemarks": [],
        "points": 105
    },
    {
        "_id": "c398eaa8",
        "name": "Fireborn",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 4
            }
        ],
        "runemarks": [
            "trapper"
        ],
        "points": 110
    },
    {
        "_id": "51a7d96c",
        "name": "Inferno Priest",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 15,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "club",
                "strength": 4
            },
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 6,
                "min_range": 0,
                "runemark": "blast",
                "strength": 3
            }
        ],
        "runemarks": [
            "mystic"
        ],
        "points": 120
    },
    {
        "_id": "40a57ff3",
        "name": "Immolator",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "unarmed",
                "strength": 4
            }
        ],
        "runemarks": [
            "destroyer"
        ],
        "points": 150
    },
    {
        "_id": "d96f656f",
        "name": "Brazen Champion",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 2,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "runemarks": [
            "brute"
        ],
        "points": 165
    },
    {
        "_id": "21f028de",
        "name": "Blazing Lord",
        "warband": "Scions of the Flame",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 5,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 6,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "sword",
                "strength": 5
            }
        ],
        "runemarks": [
            "hero",
            "brute"
        ],
        "points": 200
    }
]

=== krisling049/warcry_data/data/chaos/jade_obelisk/jade_obelisk_fighters.json
[
    {
        "_id": "3a603d57",
        "name": "Defacer with Antithete Bow",
        "warband": "Jade Obelisk",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 15,
                "min_range": 3,
                "runemark": "ranged",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 95
    },
    {
        "_id": "0107090d",
        "name": "Defacer with Stonecutter Tools",
        "warband": "Jade Obelisk",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 4
            }
        ],
        "runemarks": [
            "warrior"
        ],
        "points": 95
    },
    {
        "_id": "0f01b0fc",
        "name": "Desecrator with Iconoclast Warpick",
        "warband": "Jade Obelisk",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 5
            }
        ],
        "runemarks": [
            "destroyer"
        ],
        "points": 100
    },
    {
        "_id": "5d2df80c",
        "name": "Desecrator with Statue-Smasher Hammer",
        "warband": "Jade Obelisk",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 3,
                "max_range": 1,
                "min_range": 0,
                "runemark": "hammer",
                "strength": 5
            }
        ],
        "runemarks": [
            "destroyer"
        ],
        "points": 100
    },
    {
        "_id": "6b58ba77",
        "name": "Idolarc",
        "warband": "Jade Obelisk",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 8,
        "toughness": 3,
        "wounds": 8,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 3
            }
        ],
        "runemarks": [
            "beast",
            "fly"
        ],
        "points": 105
    },
    {
        "_id": "be116cfc",
        "name": "Nephrite Priestess",
        "warband": "Jade Obelisk",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            }
        ],
        "runemarks": [
            "hero",
            "priest"
        ],
        "points": 105
    },
    {
        "_id": "6095fdfa",
        "name": "Obelisk Bearer",
        "warband": "Jade Obelisk",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "icon-bearer"
        ],
        "points": 110
    }
]

=== krisling049/warcry_data/data/chaos/maggotkin_of_nurgle_daemons/maggotkin_of_nurgle_daemons_fighters.json
[
    {
        "_id": "bb658018",
        "name": "Plaguebearer",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            }
        ],
        "runemarks": [
            "warrior"
        ],
        "points": 60
    },
    {
        "_id": "68ef25a4",
        "name": "Plagueridden",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 15,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            }
        ],
        "runemarks": [
            "hero",
            "warrior"
        ],
        "points": 90
    },
    {
        "_id": "64aee8cd",
        "name": "Nurglings",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "toughness": 3,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 6,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 3
            }
        ],
        "runemarks": [
            "minion"
        ],
        "points": 115
    },
    {
        "_id": "384d1420",
        "name": "Poxbringer",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 7,
                "min_range": 3,
                "runemark": "blast",
                "strength": 3
            }
        ],
        "runemarks": [
            "hero"
        ],
        "points": 130
    },
    {
        "_id": "04b82f5a",
        "name": "Sloppity Bilepiper",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero",
            "agile"
        ],
        "points": 130
    },
    {
        "_id": "f252c741",
        "name": "Spoilpox Scrivener",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 3,
        "toughness": 4,
        "wounds": 22,
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 5,
                "dmg_hit": 3,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            }
        ],
        "runemarks": [
            "hero",
            "champion"
        ],
        "points": 135
    },
    {
        "_id": "872ffe2e",
        "name": "Beast of Nurgle",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 30,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 4
            }
        ],
        "runemarks": [
            "beast",
            "ferocious"
        ],
        "points": 150
    },
    {
        "_id": "67ae7666",
        "name": "Plague Drone",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 6,
        "toughness": 4,
        "wounds": 30,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "fly",
            "destroyer"
        ],
        "points": 205
    },
    {
        "_id": "f3ef89d8",
        "name": "Plaguebringer",
        "warband": "Maggotkin of Nurgle: Daemons",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 6,
        "toughness": 4,
        "wounds": 35,
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "fly",
            "hero",
            "destroyer"
        ],
        "points": 255
    }
]
