=== krisling049/warcry_data/schemas/fighter_schema.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"$id": "https://raw.githubusercontent.com/krisling049/warcry_data/main/schemas/fighter_schema.json",
	"type": "object",
	"title": "Fighter Schema",
	"required": [
		"_id",
		"subfaction",
		"grand_alliance",
		"movement",
		"name",
		"points",
		"runemarks",
		"toughness",
		"warband",
		"weapons",
		"wounds"
	],
	"properties": {
		"_id": {
			"type": "string",
			"description": "A unique ID for this fighter: 8 lowercase letters or digits, e.g. the start of a uuid4.",
			"pattern": "^[0-9a-z]{8}$",
			"examples": [
				"c0fadcc5"
			]
		},
		"subfaction": {
			"type": "string",
			"description": "If the fighter belongs to a subfaction, their subfaction warband name. Otherwise an empty string",
			"default": "",
			"examples": [
				"Hedrakka's Madmob"
			]
		},
		"grand_alliance": {
			"type": "string",
			"description": "Grand Alliance name, lowercase",
			"enum": [
				"chaos",
				"death",
				"destruction",
				"order"
			],
			"examples": [
				"destruction"
			]
		},
		"movement": {
			"type": "integer",
			"description": "Movement characteristic of the fighter",
			"examples": [
				4
			]
		},
		"name": {
			"type": "string",
			"description": "Name of the fighter as it appears on their profile card",
			"examples": [
				"Savage Orruk Arrowboy"
			]
		},
		"points": {
			"type": "integer",
			"description": "Points value of the fighter",
			"examples": [
				110
			]
		},
		"runemarks": {
			"type": "array",
			"default": [],
			"description": "Runemark names, lowercase. Do not include faction runemarks",
			"items": {
				"type": "string",
				"examples": [
					"destroyer"
				]
			}
		},
		"toughness": {
			"type": "integer",
			"description": "Toughness characteristic of the fighter",
			"examples": [
				3
			]
		},
		"warband": {
			"type": "string",
			"description": "Name of the fighter's faction, as defined by their faction runemark",
			"examples": [
				"Bonesplitterz"
			]
		},
		"weapons": {
			"type": "array",
			"description": "Each attack profile available to the fighter",
			"items": {
				"type": "object",
				"required": [
					"attacks",
					"dmg_crit",
					"dmg_hit",
					"max_range",
					"min_range",
					"runemark",
					"strength"
				],
				"properties": {
					"attacks": {
						"type": "integer",
						"examples": [
							3,
							2
						]
					},
					"dmg_crit": {
						"type": "integer",
						"examples": [
							2,
							3
						]
					},
					"dmg_hit": {
						"type": "integer",
						"examples": [
							1
						]
					},
					"max_range": {
						"type": "integer",
						"examples": [
							1,
							15
						]
					},
					"min_range": {
						"type": "integer",
						"description": "If no minimum range, use 0",
						"examples": [
							0,
							3
						]
					},
					"runemark": {
						"type": "string",
						"description": "Runemark of this weapon profile",
						"examples": [
							"unarmed",
							"ranged"
						]
					},
					"strength": {
						"type": "integer",
						"title": "The strength Schema",
						"examples": [
							3
						]
					}
				},
				"examples": [
					{
						"attacks": 3,
						"dmg_crit": 2,
						"dmg_hit": 1,
						"max_range": 1,
						"min_range": 0,
						"runemark": "unarmed",
						"strength": 3
					},
					{
						"attacks": 2,
						"dmg_crit": 3,
						"dmg_hit": 1,
						"max_range": 15,
						"min_range": 3,
						"runemark": "ranged",
						"strength": 3
					}
				]
			}
		},
		"wounds": {
			"type": "integer",
			"description": "Wounds characteristic of the fighter",
			"examples": [
				15
			]
		}
	},
	"examples": [
		{
			"_id": "c0fadcc5",
			"subfaction": "",
			"grand_alliance": "destruction",
			"movement": 4,
			"name": "Savage Orruk Arrowboy",
			"points": 110,
			"runemarks": [
				"destroyer"
			],
			"toughness": 3,
			"warband": "Bonesplitterz",
			"weapons": [
				{
					"attacks": 3,
					"dmg_crit": 2,
					"dmg_hit": 1,
					"max_range": 1,
					"min_range": 0,
					"runemark": "unarmed",
					"strength": 3
				},
				{
					"attacks": 2,
					"dmg_crit": 3,
					"dmg_hit": 1,
					"max_range": 15,
					"min_range": 3,
					"runemark": "ranged",
					"strength": 3
				}
			],
			"wounds": 15
		}
	]
}

=== krisling049/warcry_data/data/order/twistweald/twistweald_fighters.json
[
    {
        "_id": "w82oy9ke",
        "name": "Twistroot Warden with Spitespear",
        "warband": "Twistweald",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 4,
        "toughness": 5,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 4
            }
        ],
        "runemarks": [],
        "points": 115
    },
    {
        "_id": "yj5dkhz9",
        "name": "Twistroot Revenant with Harvester Blade",
        "warband": "Twistweald",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "destroyer"
        ],
        "points": 105
    },
    {
        "_id": "t6gzalfu",
        "name": "Twistroot Spite-revenant with Briarlash",
        "warband": "Twistweald",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 5
            }
        ],
        "runemarks": [
            "berserker",
            "destroyer"
        ],
        "points": 105
    },
    {
        "_id": "nxy63tdg",
        "name": "Swarmsage",
        "warband": "Twistweald",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 4,
        "toughness": 4,
        "wounds": 22,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 6,
                "dmg_hit": 3,
                "max_range": 7,
                "min_range": 3,
                "runemark": "blast",
                "strength": 4
            }
        ],
        "runemarks": [
            "berserker",
            "hero"
        ],
        "points": 180
    },
    {
        "_id": "0mn9hope",
        "name": "Twistroot Warden with Guardian Bow",
        "warband": "Twistweald",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 3
            },
            {
                "attacks": 4,
                "dmg_crit": 2,
                "dmg_hit": 1,
                "max_range": 15,
                "min_range": 3,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [],
        "points": 115
    },
    {
        "_id": "olr4u0n9",
        "name": "Twistroot Dryad",
        "warband": "Twistweald",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 5,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 4
            }
        ],
        "runemarks": [
            "destroyer"
        ],
        "points": 100
    },
    {
        "_id": "0awo336h",
        "name": "Twistroot Warden with Guardian Halberd",
        "warband": "Twistweald",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 3,
                "max_range": 2,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "runemarks": [],
        "points": 120
    }
]

=== krisling049/warcry_data/data/order/vulkyn_flameseekers/vulkyn_flameseekers_fighters.json
[
    {
        "_id": "df9fe661",
        "name": "Scalebreaker with Fyresteel Splitaxe",
        "warband": "Vulkyn Flameseekers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 3,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [
            "elite"
        ],
        "points": 95
    },
    {
        "_id": "e00e73d1",
        "name": "Scalebreaker with Bokaz",
        "warband": "Vulkyn Flameseekers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 3,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [
            "elite"
        ],
        "points": 95
    },
    {
        "_id": "56748d38",
        "name": "Kyndledroth",
        "warband": "Vulkyn Flameseekers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 4,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 4
            },
            {
                "attacks": 1,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 8,
                "min_range": 0,
                "runemark": "blast",
                "strength": 6
            }
        ],
        "runemarks": [
            "beast"
        ],
        "points": 95
    },
    {
        "_id": "8770f3ac",
        "name": "Drothmaster",
        "warband": "Vulkyn Flameseekers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 3,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [
            "elite",
            "destroyer"
        ],
        "points": 125
    },
    {
        "_id": "22956036",
        "name": "Drothblood Thane",
        "warband": "Vulkyn Flameseekers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 3,
        "toughness": 5,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "axe",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [
            "elite",
            "berserker"
        ],
        "points": 140
    },
    {
        "_id": "64ee2181",
        "name": "Vulkyn Runefather with Drothvault Greataxe",
        "warband": "Vulkyn Flameseekers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 3,
        "toughness": 5,
        "wounds": 22,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "axe",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero",
            "elite"
        ],
        "points": 150
    },
    {
        "_id": "a9d356ed",
        "name": "Vulkyn Runefather with Mastercrafted Bokaz",
        "warband": "Vulkyn Flameseekers",
        "subfaction": "",
        "grand_alliance": "order",
        "movement": 3,
        "toughness": 5,
        "wounds": 22,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 5
            },
            {
                "attacks": 2,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "ranged",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero",
            "elite"
        ],
        "points": 150
    }
]

=== krisling049/warcry_data/data/chaos/the_unmade/the_unmade_fighters.json
[
    {
        "_id": "ad8709a0",
        "name": "Awakened One with Brutal Polearm",
        "warband": "The Unmade",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 2,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 65
    },
    {
        "_id": "b2e31ca2",
        "name": "Awakened One with Flail",
        "warband": "The Unmade",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 2,
                "dmg_hit": 1,
                "max_range": 3,
                "min_range": 0,
                "runemark": "reach",
                "strength": 3
            }
        ],
        "runemarks": [],
        "points": 65
    },
    {
        "_id": "31740359",
        "name": "Ascended One",
        "warband": "The Unmade",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "sword",
                "strength": 4
            }
        ],
        "runemarks": [
            "warrior"
        ],
        "points": 110
    },
    {
        "_id": "ac71c483",
        "name": "Joyous One",
        "warband": "The Unmade",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 5,
        "toughness": 4,
        "wounds": 15,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 4
            }
        ],
        "runemarks": [
            "destroyer"
        ],
        "points": 140
    },
    {
        "_id": "9ecfd2ac",
        "name": "Blissful One",
        "warband": "The Unmade",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 8,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 6,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero"
        ],
        "points": 225
    }
]

=== krisling049/warcry_data/data/death/pyregheists/pyregheists_fighters.json
[
    {
        "_id": "8a46a02f",
        "name": "Deacon of Flames with Brazier Staff",
        "warband": "Pyregheists",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 5,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "club",
                "strength": 4
            },
            {
                "attacks": 2,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 8,
                "min_range": 0,
                "runemark": "blast",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero",
            "fly"
        ],
        "points": 190
    },
    {
        "_id": "88993788",
        "name": "Deacon of Flames with Pyrekeeper's Tongs",
        "warband": "Pyregheists",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 5,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 3,
                "max_range": 2,
                "min_range": 0,
                "runemark": "fangs",
                "strength": 5
            },
            {
                "attacks": 2,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 8,
                "min_range": 0,
                "runemark": "blast",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero",
            "fly"
        ],
        "points": 190
    },
    {
        "_id": "56aafd11",
        "name": "Balefire Guard with Scorch Flail",
        "warband": "Pyregheists",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 5,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "reach",
                "strength": 4
            }
        ],
        "runemarks": [
            "elite",
            "fly"
        ],
        "points": 130
    },
    {
        "_id": "7387b93f",
        "name": "Balefire Guard with Flaming Halberd",
        "warband": "Pyregheists",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 5,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "axe",
                "strength": 5
            }
        ],
        "runemarks": [
            "elite",
            "fly"
        ],
        "points": 130
    },
    {
        "_id": "5d752034",
        "name": "Torchwraith",
        "warband": "Pyregheists",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 6,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 8,
                "min_range": 0,
                "runemark": "blast",
                "strength": 3
            },
            {
                "attacks": 3,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "dagger",
                "strength": 3
            }
        ],
        "runemarks": [
            "frenzied",
            "fly"
        ],
        "points": 115
    },
    {
        "_id": "0a96e891",
        "name": "Flamewraith with Brazier-staff",
        "warband": "Pyregheists",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "mace",
                "strength": 4
            }
        ],
        "runemarks": [
            "fly"
        ],
        "points": 100
    },
    {
        "_id": "e87ff89f",
        "name": "Flamewraith with Balefire Torches",
        "warband": "Pyregheists",
        "subfaction": "",
        "grand_alliance": "death",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 4
            }
        ],
        "runemarks": [
            "fly"
        ],
        "points": 100
    }
]

=== krisling049/warcry_data/data/chaos/rotmire_creed/rotmire_creed_fighters.json
[
    {
        "_id": "5fde0ee8",
        "name": "Mirefolk Outcast with Bilewood Weapons",
        "warband": "Rotmire Creed",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 3,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 3,
                "dmg_hit": 1,
                "max_range": 1,
                "min_range": 0,
                "runemark": "club",
                "strength": 3
            }
        ],
        "runemarks": [
            "scout"
        ],
        "points": 65
    },
    {
        "_id": "ba18c8ea",
        "name": "Mirefolk Outcast with Bilewood Weapon and Shield",
        "warband": "Rotmire Creed",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 10,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 1,
                "max_range": 2,
                "min_range": 0,
                "runemark": "spear",
                "strength": 3
            }
        ],
        "runemarks": [
            "scout"
        ],
        "points": 75
    },
    {
        "_id": "9eaa12db",
        "name": "Carrion Catcher with Snatcher-hook",
        "warband": "Rotmire Creed",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 4,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "hook",
                "strength": 4
            }
        ],
        "runemarks": [
            "scout",
            "destroyer"
        ],
        "points": 100
    },
    {
        "_id": "1988c69e",
        "name": "Carrion Catcher with Impaler",
        "warband": "Rotmire Creed",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 12,
        "weapons": [
            {
                "attacks": 3,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 2,
                "min_range": 0,
                "runemark": "scythe",
                "strength": 4
            }
        ],
        "runemarks": [
            "scout"
        ],
        "points": 105
    },
    {
        "_id": "680fcbe7",
        "name": "Bloated one with Raker-claw and Hooked Net",
        "warband": "Rotmire Creed",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 4
            }
        ],
        "runemarks": [
            "brute",
            "trapper"
        ],
        "points": 140
    },
    {
        "_id": "d3377614",
        "name": "Bloated One with Raker-claws",
        "warband": "Rotmire Creed",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 18,
        "weapons": [
            {
                "attacks": 5,
                "dmg_crit": 5,
                "dmg_hit": 2,
                "max_range": 1,
                "min_range": 0,
                "runemark": "claws",
                "strength": 4
            }
        ],
        "runemarks": [
            "brute"
        ],
        "points": 145
    },
    {
        "_id": "6407f2f9",
        "name": "Witherlord",
        "warband": "Rotmire Creed",
        "subfaction": "",
        "grand_alliance": "chaos",
        "movement": 4,
        "toughness": 4,
        "wounds": 20,
        "weapons": [
            {
                "attacks": 4,
                "dmg_crit": 5,
                "dmg_hit": 3,
                "max_range": 2,
                "min_range": 0,
                "runemark": "hook",
                "strength": 4
            }
        ],
        "runemarks": [
            "hero",
            "destroyer"
        ],
        "points": 175
    }
]
